import type { Page, Request, Response, TestInfo } from '@playwright/test';
import { expect, test } from '@playwright/test';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { PNG } from 'pngjs';
import pixelmatch from 'pixelmatch';

export type CheckpointMode = 'off' | 'capture' | 'compare';

const MODE = (process.env.CHECKPOINT_MODE ?? 'off') as CheckpointMode;
// Default to the repo-local baseline/ dir. Override via QA_CHECKPOINT_ROOT for
// cross-branch comparisons (see scripts/compare-against-main.sh).
const ROOT = process.env.QA_CHECKPOINT_ROOT
  ? path.resolve(process.env.QA_CHECKPOINT_ROOT)
  : path.resolve(__dirname, '..', 'baseline');
// True pixel-level comparison via pixelmatch. Fraction of differing pixels
// allowed before the checkpoint fails. 0.001 = 0.1% of pixels may drift.
// Small text antialiasing is handled by pixelmatch's threshold param below,
// so this stays low and still catches tiny regressions like a recolored button.
// 1% of pixels — tolerates IPN text in page title (fresh seed parts per run)
// and single-row table additions, still catches any multi-button color
// change, layout shift, or element removal.
const PIXEL_DIFF_RATIO = Number(process.env.CHECKPOINT_PIXEL_DIFF_RATIO ?? '0.01');
const PIXEL_MATCH_THRESHOLD = Number(process.env.CHECKPOINT_PIXEL_THRESHOLD ?? '0.1');

type PageState = {
  requests: Array<{ method: string; url: string }>;
  counter: number;
};

const state: WeakMap<Page, PageState> = new WeakMap();

function installListener(page: Page): PageState {
  const existing = state.get(page);
  if (existing) return existing;
  const s: PageState = { requests: [], counter: 0 };
  state.set(page, s);
  page.on('request', (req: Request) => {
    const url = req.url();
    if (!/\/api\//.test(url)) return;
    s.requests.push({ method: req.method(), url });
  });
  return s;
}

function slugify(s: string): string {
  return s
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase()
    .slice(0, 80);
}

/**
 * Strip values that change between runs even when the feature behaves
 * identically. Add patterns here as we find new classes of flakiness.
 */
export function maskHtml(html: string): string {
  return (
    html
      // ISO timestamps
      .replace(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z?/g, '<TS>')
      // Human relative times
      .replace(/\b\d+\s+(seconds?|minutes?|hours?|days?|weeks?|months?|years?)\s+ago\b/gi, '<AGO>')
      // Numeric pks in URLs
      .replace(/\/(\d{3,})\//g, '/<PK>/')
      // data-pk / data-id / data-key attributes
      .replace(/(data-(?:pk|id|key|test-id|index|uid))="[^"]*"/gi, '$1="<ID>"')
      // Bare pk/id values in form inputs: value="640", href="/640/"
      .replace(/\bvalue="\d{3,}"/g, 'value="<ID>"')
      .replace(/\bhref="[^"]*\/\d{3,}(?:\/|")/g, (m) => m.replace(/\d{3,}/, '<ID>'))
      // Timestamped session tags + base36 timestamps: UI-REL-A-1744654321, QAP-UI-mnyrkolld8
      .replace(/([A-Z]{2,}-)\d{10,}/g, '$1<TS>')
      .replace(/\bQAP-UI-[a-z0-9]+/g, 'QAP-UI-<TS>')
      .replace(/\bQA-UI-Part-[a-z0-9]+/g, 'QA-UI-Part-<TS>')
      .replace(/\bUI-[A-Z]+(?:-[A-Z]+)*-[a-z0-9]{6,}/g, 'UI-<AREA>-<TS>')
      // CSRF tokens and similar long secrets
      .replace(/(csrfmiddlewaretoken|csrf[-_]?token)["':=\s]+[A-Za-z0-9_-]{16,}/gi, '$1=<TOK>')
      // Autogenerated element ids — React/Mantine hashes like "_r_ms_", "r5b", "mantine-4j9su24z2"
      .replace(/\bid="[a-z0-9_-]+"/gi, 'id="<HASH>"')
      .replace(/\baria-controls="[a-z0-9_-]+"/gi, 'aria-controls="<HASH>"')
      .replace(/\baria-describedby="[a-z0-9_-]+"/gi, 'aria-describedby="<HASH>"')
      .replace(/\baria-labelledby="[a-z0-9_-]+"/gi, 'aria-labelledby="<HASH>"')
      .replace(/\bfor="[a-z0-9_-]+"/gi, 'for="<HASH>"')
      // SVG clip/gradient ids
      .replace(/url\(#[a-z0-9-]{4,}\)/gi, 'url(#<HASH>)')
      // Mantine per-render class suffixes like __m__-_r_8l_
      .replace(/__m__-_r_[a-z0-9]+_/g, '__m__-_r_<HASH>_')
      // Mantine component ids like mantine-4j9su24z2 embedded anywhere
      .replace(/\bmantine-[a-z0-9]{6,}/g, 'mantine-<HASH>')
      // React/emotion generated class names like "css-1abc2de" or "e1abcd2"
      .replace(/\bcss-[a-z0-9]{5,}\b/gi, 'css-<HASH>')
      .replace(/\bemotion-[a-z0-9]{5,}\b/gi, 'emotion-<HASH>')
      // Vite asset fingerprints: MobileAppView-CwRXs3sX.js
      .replace(/-[A-Za-z0-9_-]{8}\.(js|css|woff2?|svg|png)\b/g, '-<FP>.$1')
      // Strip every inline style attribute — CSS variables (scroll thumb widths,
      // computed position offsets) change per render based on viewport metrics.
      // Layout regressions are still caught by the PNG baseline; HTML is for
      // DOM-structural drift only.
      .replace(/\sstyle="[^"]*"/g, '')
      // Collapse whitespace runs so layout wobble doesn't cause diffs
      .replace(/\s+/g, ' ')
      .trim()
  );
}

export function maskRequestUrl(url: string): string {
  return url
    .replace(/^https?:\/\/[^/]+/, '')
    .replace(/\/(\d{3,})\//g, '/<PK>/')
    .replace(/\/(\d{3,})(?=\?|$)/g, '/<PK>')
    .replace(/([?&])(search|name|IPN|description)=[^&]+/g, '$1$2=<V>')
    // Numeric pk in any query parameter value
    .replace(/([?&])([a-z_]+)=\d{3,}/gi, '$1$2=<PK>')
    .replace(/([?&])timestamp=[^&]+/g, '$1timestamp=<TS>');
}

async function writeFile(p: string, body: string): Promise<void> {
  await fs.mkdir(path.dirname(p), { recursive: true });
  await fs.writeFile(p, body, 'utf8');
}

async function readIfExists(p: string): Promise<string | null> {
  try {
    return await fs.readFile(p, 'utf8');
  } catch {
    return null;
  }
}

/**
 * Capture or compare a checkpoint at the current page state.
 *
 * Env-driven:
 * - CHECKPOINT_MODE=capture → write baseline PNG/HTML/requests
 * - CHECKPOINT_MODE=compare → read baseline and assert equality (with masking)
 * - CHECKPOINT_MODE unset or 'off' → no-op (zero overhead in normal runs)
 *
 * The baseline layout is:
 *   automation/ui/baseline/<test-slug>/<step>.png
 *   automation/ui/baseline/<test-slug>/<step>.html
 *   automation/ui/baseline/<test-slug>/<step>.requests.json
 */
export async function captureCheckpoint(
  page: Page,
  stepName: string,
  opts: { selector?: string; maxDiffPixels?: number } = {},
): Promise<void> {
  if (MODE === 'off') return;

  const info: TestInfo = test.info();
  const pageState = installListener(page);
  pageState.counter += 1;

  const testSlug = slugify(`${path.basename(info.file, '.spec.ts')}-${info.title}`);
  const stepSlug = `${String(pageState.counter).padStart(2, '0')}-${slugify(stepName)}`;
  const dir = path.join(ROOT, testSlug);

  // Give the page a beat to settle animations/network before snapping.
  await page.waitForLoadState('networkidle').catch(() => undefined);
  await page.waitForTimeout(300);

  const pngPath = path.join(dir, `${stepSlug}.png`);
  const htmlPath = path.join(dir, `${stepSlug}.html`);
  const reqPath = path.join(dir, `${stepSlug}.requests.json`);

  const target = opts.selector ? page.locator(opts.selector) : page;
  const pngBuffer = await (target as Page).screenshot({
    fullPage: false,
    animations: 'disabled',
    caret: 'hide',
  });

  const rawHtml = await page.evaluate(() => document.documentElement.outerHTML);
  const maskedHtml = maskHtml(rawHtml);
  const maskedRequests = pageState.requests.map((r) => ({
    method: r.method,
    url: maskRequestUrl(r.url),
  }));
  pageState.requests.length = 0; // reset window for next checkpoint
  const requestsJson = JSON.stringify(maskedRequests, null, 2);

  if (MODE === 'capture') {
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(pngPath, pngBuffer);
    await writeFile(htmlPath, maskedHtml);
    await writeFile(reqPath, requestsJson);
    info.annotations.push({ type: 'checkpoint-captured', description: `${testSlug}/${stepSlug}` });
    return;
  }

  // compare mode
  const errors: string[] = [];

  const baselinePng = await fs.readFile(pngPath).catch(() => null);
  if (!baselinePng) {
    errors.push(`missing baseline PNG: ${pngPath}`);
  } else {
    try {
      const basePngObj = PNG.sync.read(baselinePng);
      const curPngObj = PNG.sync.read(pngBuffer);
      if (basePngObj.width !== curPngObj.width || basePngObj.height !== curPngObj.height) {
        const actualPath = path.join(dir, `${stepSlug}.actual.png`);
        await fs.writeFile(actualPath, pngBuffer);
        errors.push(
          `PNG dimensions differ (baseline ${basePngObj.width}x${basePngObj.height}, actual ${curPngObj.width}x${curPngObj.height}) — see ${actualPath}`,
        );
      } else {
        const { width, height } = basePngObj;
        const diff = new PNG({ width, height });
        const diffPixels = pixelmatch(
          basePngObj.data,
          curPngObj.data,
          diff.data,
          width,
          height,
          { threshold: PIXEL_MATCH_THRESHOLD },
        );
        const totalPixels = width * height;
        const ratio = diffPixels / totalPixels;
        const maxRatio = opts.maxDiffPixels ?? PIXEL_DIFF_RATIO;
        if (ratio > maxRatio) {
          const actualPath = path.join(dir, `${stepSlug}.actual.png`);
          const diffPath = path.join(dir, `${stepSlug}.diff.png`);
          await fs.writeFile(actualPath, pngBuffer);
          await fs.writeFile(diffPath, PNG.sync.write(diff));
          errors.push(
            `PNG differs: ${diffPixels} / ${totalPixels} px (${(ratio * 100).toFixed(3)}% > ${(maxRatio * 100).toFixed(3)}%) — see ${actualPath} + ${diffPath}`,
          );
        }
      }
    } catch (e) {
      errors.push(`PNG compare failed: ${(e as Error).message}`);
    }
  }

  const baselineHtml = await readIfExists(htmlPath);
  if (baselineHtml === null) {
    errors.push(`missing baseline HTML: ${htmlPath}`);
  } else if (baselineHtml !== maskedHtml) {
    const actualPath = path.join(dir, `${stepSlug}.actual.html`);
    await writeFile(actualPath, maskedHtml);
    errors.push(`HTML differs — see ${actualPath}`);
  }

  const baselineRequests = await readIfExists(reqPath);
  if (baselineRequests === null) {
    errors.push(`missing baseline requests: ${reqPath}`);
  } else if (baselineRequests.trim() !== requestsJson.trim()) {
    const actualPath = path.join(dir, `${stepSlug}.actual.requests.json`);
    await writeFile(actualPath, requestsJson);
    errors.push(`Requests differ — see ${actualPath}`);
  }

  expect(errors, `checkpoint ${testSlug}/${stepSlug}\n${errors.join('\n')}`).toEqual([]);
}

/**
 * Reset the per-page request buffer without emitting a checkpoint.
 * Useful when a test performs setup requests you don't want to include
 * in the first real checkpoint.
 */
export function resetCheckpointRequests(page: Page): void {
  const s = state.get(page);
  if (s) s.requests.length = 0;
}
