import { promises as fs } from 'node:fs';
import { resolve } from 'node:path';

const HERE = new URL('.', import.meta.url).pathname;
const VAULT_QA = resolve(HERE, '../../../docs/qa');
const OUT = resolve(HERE, '../../test-cases/api-manual-tests.md');

const AREAS = [
  { slug: 'crud', title: 'Parts CRUD' },
  { slug: 'query', title: 'List, filter, search, pagination' },
  { slug: 'category', title: 'Part Category' },
  { slug: 'bom', title: 'Bill of Materials' },
  { slug: 'negative', title: 'Negative / auth / validation' },
];

type Row = { oldId: string; rest: string };

function parseAreaFile(md: string): { headerLine: string; rows: Row[]; trailing: string[] } {
  const lines = md.split(/\r?\n/);
  let headerLine = '';
  const rows: Row[] = [];
  const trailing: string[] = [];
  let inTable = false;
  let sawSeparator = false;
  for (const line of lines) {
    if (!inTable && /^\|\s*ID\s*\|/.test(line)) {
      headerLine = line.trim();
      inTable = true;
      continue;
    }
    if (inTable && !sawSeparator && /^\|\s*[-: ]+\|/.test(line)) {
      sawSeparator = true;
      continue;
    }
    if (inTable) {
      const m = /^\|\s*(API-PARTS-\d{3,})\s*(\|.*)$/.exec(line);
      if (m && m[1] && m[2]) {
        rows.push({ oldId: m[1], rest: m[2] });
      } else if (line.trim() === '') {
        // allowed inside table block
      } else {
        inTable = false;
        if (line.trim()) trailing.push(line);
      }
    } else if (line.trim()) {
      trailing.push(line);
    }
  }
  return { headerLine, rows, trailing };
}

const pad3 = (n: number) => String(n).padStart(3, '0');

async function main() {
  type AreaResult = {
    slug: string;
    title: string;
    headerLine: string;
    rows: Row[];
    trailing: string[];
  };
  const areas: AreaResult[] = [];
  for (const a of AREAS) {
    const path = resolve(VAULT_QA, `phase2-api-${a.slug}.md`);
    let md: string;
    try {
      md = await fs.readFile(path, 'utf8');
    } catch {
      console.error(`[merge-api] missing: ${path}`);
      continue;
    }
    const parsed = parseAreaFile(md);
    if (!parsed.headerLine) {
      console.error(`[merge-api] no table header in ${a.slug}, skipping`);
      continue;
    }
    areas.push({ slug: a.slug, title: a.title, ...parsed });
  }

  const idMap = new Map<string, string>();
  let counter = 0;
  for (const area of areas) {
    for (const row of area.rows) {
      counter += 1;
      const newId = `API-PARTS-${pad3(counter)}`;
      idMap.set(`${area.slug}:${row.oldId}`, newId);
    }
  }

  const canonicalHeader =
    areas[0]?.headerLine ??
    '| ID | Endpoint | Method | Title | Preconditions | Payload | Expected Status | Expected Body | Priority | Tags |';
  const columnCount = (canonicalHeader.match(/\|/g)?.length ?? 0) - 1;
  const separator = '|' + Array(columnCount).fill('---').join('|') + '|';

  const lines: string[] = [];
  lines.push('# API manual test cases — InvenTree Parts');
  lines.push('');
  lines.push(
    `Generated by \`submission/agents/rag/merge-api-cases.ts\` from five per-area drafts in \`docs/qa/phase2-api-*.md\`. Each draft is the raw output of a grounded RAG call to \`qa-gemma\` (qwen2.5-coder:7b @ 100% GPU) using the filtered InvenTree OpenAPI (\`submission/data/openapi-parts.filtered.json\`) as the retrieval corpus.`,
  );
  lines.push('');
  lines.push(`**Total cases: ${counter}**`);
  lines.push('');
  lines.push('## Table of contents');
  lines.push('');
  let seen = 0;
  for (const area of areas) {
    if (area.rows.length === 0) continue;
    const first = pad3(seen + 1);
    const last = pad3(seen + area.rows.length);
    lines.push(
      `- [${area.title}](#${area.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}) — API-PARTS-${first}..${last} (${area.rows.length} cases)`,
    );
    seen += area.rows.length;
  }
  lines.push('');

  let running = 0;
  for (const area of areas) {
    if (area.rows.length === 0) continue;
    lines.push(`## ${area.title}`);
    lines.push('');
    lines.push(canonicalHeader);
    lines.push(separator);
    for (const row of area.rows) {
      running += 1;
      lines.push(`| API-PARTS-${pad3(running)} ${row.rest}`);
    }
    lines.push('');
    for (const t of area.trailing) {
      if (/^NEED_CONTEXT/i.test(t)) lines.push(`> **gap** — ${t}`);
      else lines.push(`> ${t}`);
    }
    if (area.trailing.length) lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('## ID mapping (old → new)');
  lines.push('');
  lines.push('| area | old | new |');
  lines.push('|---|---|---|');
  for (const [key, newId] of idMap.entries()) {
    const [slug, oldId] = key.split(':');
    lines.push(`| ${slug} | ${oldId} | ${newId} |`);
  }
  lines.push('');

  await fs.mkdir(resolve(HERE, '../../test-cases'), { recursive: true });
  await fs.writeFile(OUT, lines.join('\n'), 'utf8');
  console.error(`[merge-api] wrote ${OUT}`);
  console.error(`[merge-api] ${counter} cases across ${areas.length} areas`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
