import { promises as fs } from 'node:fs';
import { resolve } from 'node:path';

const HERE = new URL('.', import.meta.url).pathname;
const VAULT_QA = resolve(HERE, '../../../docs/qa');
const OUT = resolve(HERE, '../../test-cases/ui-manual-tests.md');

// Ordered like a table of contents — not alphabetical.
const AREAS = [
  { slug: 'creation', title: 'Creation' },
  { slug: 'tabs', title: 'Part detail tabs' },
  { slug: 'categories', title: 'Categories' },
  { slug: 'attributes', title: 'Part attributes' },
  { slug: 'units', title: 'Units of measure' },
  { slug: 'parameters', title: 'Parameters' },
  { slug: 'templates', title: 'Template & variants' },
  { slug: 'revisions', title: 'Revisions' },
  { slug: 'negative', title: 'Negative / validation' },
];

type Row = {
  oldId: string;
  rest: string; // everything after the ID column, including the leading `|`
};

type AreaResult = {
  slug: string;
  title: string;
  headerLine: string;
  rows: Row[];
  trailing: string[]; // NEED_CONTEXT lines and stray prose after the table
};

function parseAreaFile(md: string): { headerLine: string; rows: Row[]; trailing: string[] } {
  const lines = md.split(/\r?\n/);
  let headerLine = '';
  const rows: Row[] = [];
  const trailing: string[] = [];
  let inTable = false;
  let sawSeparator = false;
  for (const line of lines) {
    if (!inTable && /^\|\s*ID\s*\|/.test(line)) {
      headerLine = line.trim();
      inTable = true;
      continue;
    }
    if (inTable && !sawSeparator && /^\|\s*[-: ]+\|/.test(line)) {
      sawSeparator = true;
      continue;
    }
    if (inTable) {
      const m = /^\|\s*(UI-PARTS-\d{3,})\s*(\|.*)$/.exec(line);
      if (m && m[1] && m[2]) {
        rows.push({ oldId: m[1], rest: m[2] });
      } else if (line.trim() === '') {
        // blank line allowed inside table area
      } else {
        // anything else after the last row — stop table, collect as trailing
        inTable = false;
        if (line.trim()) trailing.push(line);
      }
    } else if (line.trim()) {
      trailing.push(line);
    }
  }
  return { headerLine, rows, trailing };
}

function pad3(n: number): string {
  return String(n).padStart(3, '0');
}

async function main() {
  const areas: AreaResult[] = [];
  for (const a of AREAS) {
    const path = resolve(VAULT_QA, `phase1-ui-${a.slug}.md`);
    let md: string;
    try {
      md = await fs.readFile(path, 'utf8');
    } catch {
      console.error(`[merge] missing: ${path}`);
      continue;
    }
    const parsed = parseAreaFile(md);
    if (!parsed.headerLine) {
      console.error(`[merge] no table header in ${a.slug}, skipping`);
      continue;
    }
    areas.push({ slug: a.slug, title: a.title, ...parsed });
  }

  // Renumber sequentially across all areas
  const idMap = new Map<string, string>(); // oldId -> newId (per-area scoped via slug prefix)
  let counter = 0;
  for (const area of areas) {
    for (const row of area.rows) {
      counter += 1;
      const newId = `UI-PARTS-${pad3(counter)}`;
      idMap.set(`${area.slug}:${row.oldId}`, newId);
    }
  }

  // Take the first non-empty header as the canonical column schema
  const canonicalHeader =
    areas.find((a) => a.headerLine)?.headerLine ??
    '| ID | Title | Preconditions | Steps | Expected | Priority | Tags |';
  const columnCount = (canonicalHeader.match(/\|/g)?.length ?? 0) - 1;
  const separator = '|' + Array(columnCount).fill('---').join('|') + '|';

  const lines: string[] = [];
  lines.push('# UI manual test cases — InvenTree Parts');
  lines.push('');
  lines.push(
    `Generated by \`submission/agents/rag/merge-ui-cases.ts\` from nine per-area drafts in \`docs/qa/phase1-ui-*.md\`. Each draft is the raw output of a grounded RAG call to \`qa-gemma\` (qwen2.5-coder:7b @ 100% GPU) with the retrieval context shown in \`docs/qa/prompts-journal.md\`.`,
  );
  lines.push('');
  lines.push(`**Total cases: ${counter}**`);
  lines.push('');
  lines.push('## Table of contents');
  lines.push('');
  let seen = 0;
  for (const area of areas) {
    if (area.rows.length === 0) continue;
    const first = pad3(seen + 1);
    const last = pad3(seen + area.rows.length);
    lines.push(`- [${area.title}](#${area.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}) — UI-PARTS-${first}..${last} (${area.rows.length} cases)`);
    seen += area.rows.length;
  }
  lines.push('');

  let running = 0;
  for (const area of areas) {
    if (area.rows.length === 0) continue;
    lines.push(`## ${area.title}`);
    lines.push('');
    lines.push(canonicalHeader);
    lines.push(separator);
    for (const row of area.rows) {
      running += 1;
      const newId = `UI-PARTS-${pad3(running)}`;
      lines.push(`| ${newId} ${row.rest}`);
    }
    lines.push('');
    if (area.trailing.length > 0) {
      for (const t of area.trailing) {
        if (/^NEED_CONTEXT/i.test(t)) {
          lines.push(`> **gap** — ${t}`);
        } else {
          lines.push(`> ${t}`);
        }
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('## ID mapping (old → new)');
  lines.push('');
  lines.push('| area | old | new |');
  lines.push('|---|---|---|');
  for (const [key, newId] of idMap.entries()) {
    const [slug, oldId] = key.split(':');
    lines.push(`| ${slug} | ${oldId} | ${newId} |`);
  }
  lines.push('');

  await fs.mkdir(resolve(HERE, '../../test-cases'), { recursive: true });
  await fs.writeFile(OUT, lines.join('\n'), 'utf8');
  console.error(`[merge] wrote ${OUT}`);
  console.error(`[merge] ${counter} cases across ${areas.length} areas`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
