// render-coverage-timeline.ts — read docs/qa/snapshots/coverage-timeline.csv
// and emit a markdown page with a tiny ascii bar chart + tabular history.
// Consumed by docs/qa/snapshots/index.md; regenerated by CI after every
// main-branch baseline capture.

import { promises as fs } from 'node:fs';
import path from 'node:path';

const HERE = new URL('.', import.meta.url).pathname;
// HERE = submission/agents/rag/, two levels up = submission/
const SUBMISSION = path.resolve(HERE, '..', '..');
const CSV = path.resolve(SUBMISSION, 'docs/qa/snapshots/coverage-timeline.csv');
const OUT = path.resolve(SUBMISSION, 'docs/qa/snapshots/index.md');
const BAR_WIDTH = 40;

type Row = {
  timestamp: string;
  covered: number;
  total: number;
  ratio: number;
  ui: number;
  api: number;
  sha: string;
};

function bar(ratio: number): string {
  const filled = Math.round((ratio / 100) * BAR_WIDTH);
  return '█'.repeat(filled) + '░'.repeat(BAR_WIDTH - filled);
}

async function main(): Promise<void> {
  let text: string;
  try {
    text = await fs.readFile(CSV, 'utf8');
  } catch {
    console.error(`[timeline] no CSV at ${CSV} — skipping render`);
    process.exit(0);
  }
  const lines = text.trim().split('\n').slice(1); // skip header
  if (lines.length === 0) {
    console.error('[timeline] CSV has no data rows');
    process.exit(0);
  }
  const rows: Row[] = lines.map((l) => {
    const [timestamp, covered, total, ratio, ui, api, sha] = l.split(',');
    return {
      timestamp: timestamp!,
      covered: Number(covered),
      total: Number(total),
      ratio: Number(ratio),
      ui: Number(ui),
      api: Number(api),
      sha: (sha ?? '').trim(),
    };
  });

  const latest = rows[rows.length - 1]!;
  const first = rows[0]!;
  const delta = latest.ratio - first.ratio;
  const deltaSign = delta > 0 ? '+' : '';

  const md: string[] = [];
  md.push('---');
  md.push('title: "Coverage timeline"');
  md.push('tags: [qa, coverage, history, snapshot]');
  md.push(`generated: ${new Date().toISOString()}`);
  md.push('---');
  md.push('');
  md.push('# Coverage timeline');
  md.push('');
  md.push(
    'Automatically appended on every main-branch CI run (see `.github/workflows/qa.yml` → "Append coverage-timeline row"). Each row records the UI→API coverage state captured immediately after the baseline artefact upload.',
  );
  md.push('');
  md.push(`**Latest**: ${latest.covered}/${latest.total} (${latest.ratio.toFixed(1)}%) at ${latest.timestamp} · sha \`${latest.sha.slice(0, 8)}\``);
  md.push('');
  md.push(
    `**Delta over ${rows.length} snapshots**: ${deltaSign}${delta.toFixed(1)} pp  (${first.covered} → ${latest.covered} covered, ${first.ui} → ${latest.ui} UI specs, ${first.api} → ${latest.api} API specs)`,
  );
  md.push('');
  md.push('## Progress bar');
  md.push('');
  md.push('```');
  md.push('  date                 %   bar' + ' '.repeat(BAR_WIDTH - 1) + 'covered');
  for (const r of rows) {
    const date = r.timestamp.slice(0, 10);
    const pct = r.ratio.toFixed(1).padStart(5);
    const b = bar(r.ratio);
    md.push(`  ${date}     ${pct}%  ${b}   ${r.covered}/${r.total}`);
  }
  md.push('```');
  md.push('');
  md.push('## Full history');
  md.push('');
  md.push('| timestamp | covered | total | ratio | UI specs | API specs | sha |');
  md.push('|---|---:|---:|---:|---:|---:|---|');
  for (const r of rows) {
    md.push(
      `| ${r.timestamp} | ${r.covered} | ${r.total} | ${r.ratio.toFixed(2)}% | ${r.ui} | ${r.api} | \`${r.sha.slice(0, 8)}\` |`,
    );
  }
  md.push('');
  md.push('## Related');
  md.push('');
  md.push('- [[coverage/coverage-index|Current feature-area coverage index]]');
  md.push('- [[graph/index|Endpoint ⇄ test graph]]');
  md.push('- [[ui-paths/index|UI click-path tree]]');
  md.push('');

  await fs.writeFile(OUT, md.join('\n'));
  console.log(`[timeline] wrote ${OUT} — ${rows.length} row(s)`);
}

main().catch((e: unknown) => {
  console.error(e);
  process.exit(1);
});
